services:
  journiv:
    image: swalabtech/journiv-app:latest
    container_name: journiv
    ports:
      # if you want to expose on a different port, change the left hand side of colon to the port
      # you want to expose on do not change the 8000 on the right hand side
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-here # (REQUIRED) Replace with a strong secret key
      - DOMAIN_NAME=192.168.1.1 # (REQUIRED) Your server IP or domain
    volumes:
      - journiv_data:/data
    restart: unless-stopped

volumes:
  journiv_data:
